# -*- coding: utf-8 -*-
"""NSL_KDD Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qTC3x7yFea3wtTj-cDRws6bfQGMKIn7T

**Data and Library setup**
"""

#!pip install matplotlib seaborn -q
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

columns = [
    'duration','protocol_type','service','flag','src_bytes','dst_bytes',
    'land','wrong_fragment','urgent','hot','num_failed_logins',
    'logged_in','num_compromised','root_shell','su_attempted',
    'num_root','num_file_creations','num_shells','num_access_files',
    'num_outbound_cmds','is_host_login','is_guest_login','count',
    'srv_count','serror_rate','srv_serror_rate','rerror_rate',
    'srv_rerror_rate','same_srv_rate','diff_srv_rate',
    'srv_diff_host_rate','dst_host_count','dst_host_srv_count',
    'dst_host_same_srv_rate','dst_host_diff_srv_rate',
    'dst_host_same_src_port_rate','dst_host_srv_diff_host_rate',
    'dst_host_serror_rate','dst_host_srv_serror_rate',
    'dst_host_rerror_rate','dst_host_srv_rerror_rate',
    'label','difficulty'
]

data_train=pd.read_csv('/content/KDDTrain+.txt',names=columns)
data_test=pd.read_csv('/content/KDDTest+.txt',names=columns)

data=pd.concat([data_train,data_test])

data=data.reset_index(drop=True)

data.head()

data.info()

print(data['protocol_type'].unique())
print(data['service'].unique())
print(data['flag'].unique())
print(data['label'].unique())
print(data['label'].unique())

"""**EDA- Exploratory Data Analysis**"""

label_map = {
    'normal': 'normal',
    'neptune':'DoS','back':'DoS','land':'DoS','pod':'DoS',
    'smurf':'DoS','teardrop':'DoS','mailbomb':'DoS',
    'apache2':'DoS','processtable':'DoS','udpstorm':'DoS',
    'ipsweep':'Probe','nmap':'Probe','portsweep':'Probe',
    'satan':'Probe','mscan':'Probe','saint':'Probe',
    'ftp_write':'R2L','guess_passwd':'R2L','imap':'R2L',
    'multihop':'R2L','phf':'R2L','spy':'R2L','warezclient':'R2L',
    'warezmaster':'R2L','sendmail':'R2L','named':'R2L',
    'snmpgetattack':'R2L','snmpguess':'R2L','xlock':'R2L',
    'xsnoop':'R2L','worm':'R2L',
    'buffer_overflow':'U2R','loadmodule':'U2R','perl':'U2R',
    'rootkit':'U2R','httptunnel':'U2R','ps':'U2R',
    'sqlattack':'U2R','xterm':'U2R'
}

data['attack']=data['label'].map(label_map)
data.drop('label',axis=1,inplace=True)
data['attack'].value_counts()

data['attack'].isnull().sum()

data.dropna(subset='attack',inplace=True)

data.head()

"""**Pre-Processing and Feature Enginnering**"""

plt.figure(figsize=(10,10))
sns.countplot(x='attack',data=data)
plt.title('Attack Distribution')
plt.xticks(rotation=20)
plt.show()

df_num = data.select_dtypes(include='number').drop('difficulty', axis=1)
plt.figure(figsize=(14,10))
sns.heatmap(df_num.corr())
plt.title('Feature correlation heatmap')
plt.tight_layout()
plt.savefig('eda_heatmap.png', dpi=150)
plt.show()

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

cat_colms=['protocol_type','service','flag']
lb=LabelEncoder()
for col in cat_colms:
  data[col]=lb.fit_transform(data[col])

x=data.drop(['attack','difficulty'],axis=1)
y=data['attack']

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42,stratify=y)

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

print(y_train.unique())

sc=StandardScaler()
x_train_sc=sc.fit_transform(x_train)
x_test_sc=sc.transform(x_test)

"""**Model Training and Evaluating**"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

lr=LogisticRegression(random_state=12345)
lr.fit(x_train_sc,y_train)
y_pred=lr.predict(x_test_sc)

print("=== Logistic Regression ===")
print(f'Accuracy Score {accuracy_score(y_test,y_pred)}')
print(f'Confusion Matrix {confusion_matrix(y_test,y_pred)}')
print(f'Classification Report {classification_report(y_test,y_pred)}')

from sklearn.tree import DecisionTreeClassifier, plot_tree

dt=DecisionTreeClassifier(max_depth=8,class_weight='balanced',random_state=12345)
dt.fit(x_train,y_train)
y_pred_dt=dt.predict(x_test)

print("=== Decision Tree ===")
print(f'Accuracy Score {accuracy_score(y_test,y_pred_dt)}')
print(f'Confusion Matrix {confusion_matrix(y_test,y_pred)}')
print(f'Classification Report {classification_report(y_test,y_pred)}')

print(dt.classes_)

plt.figure(figsize=(20,20))
plot_tree(dt,max_depth=3,feature_names=x.columns,filled=True,class_names=[str(i) for i in dt.classes_],fontsize=8)
plt.title('Decision Tree - First three layouts')
plt.show()

from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(n_estimators=50,class_weight='balanced',random_state=12345,n_jobs=-1)
rfc.fit(x_train,y_train)
y_pred_rfc=rfc.predict(x_test)
x_pred_rfc=rfc.predict(x_train)

print("=== Random Forest ===")
print(f'Accuracy Score on Test: {accuracy_score(y_test,y_pred_rfc)}')
print(f'Accuracy Score on Train: {accuracy_score(y_train,x_pred_rfc)}')
print(f'Confusion Matrix {confusion_matrix(y_test,y_pred_rfc)}')
print(f'Classification Report {classification_report(y_test,y_pred_rfc)}')

important=pd.Series(rfc.feature_importances_,index=x.columns)
top15=important.nlargest(15)

plt.figure(figsize=(10,10))
top15.sort_values().plot(kind='barh')
plt.title('Top 15 Important Features')
plt.show()

import joblib

joblib.dump(lr,'logistic_regression.pkl')
joblib.dump(dt,'decision_tree.pkl')
joblib.dump(rfc,'random_forest.pkl')
joblib.dump(sc,'standard_scaler.pkl')
print('All models saved')

joblib.dump(list(x.columns), 'feature_columns.pkl')

# Get one real sample of each attack type from your actual dataset
for attack in ['DoS', 'Probe', 'R2L', 'U2R', 'normal']:
    sample = data[data['attack'] == attack].iloc[0]
    print(f"\n--- {attack} ---")
    print(sample[['src_bytes', 'dst_bytes', 'count', 'srv_count',
                  'same_srv_rate', 'diff_srv_rate',
                  'dst_host_srv_count', 'dst_host_same_srv_rate']])

# Test each scenario before updating the app
scenarios = {
    'DoS':    [0,   0,    123, 6,  0.05, 0.07, 26,  0.1],
    'Probe':  [18,  0,    1,   1,  1.0,  0.0,  16,  1.0],
    'R2L':    [334, 0,    2,   2,  1.0,  0.0,  20,  1.0],
    'U2R':    [621, 8356, 1,   1,  1.0,  0.0,  4,   0.02],
    'normal': [491, 0,    2,   2,  1.0,  0.0,  25,  0.17],
}

feature_cols = joblib.load('feature_columns.pkl')

for name, vals in scenarios.items():
    feat_dict = {col: 0 for col in feature_cols}
    feat_dict['src_bytes']               = vals[0]
    feat_dict['dst_bytes']               = vals[1]
    feat_dict['count']                   = vals[2]
    feat_dict['srv_count']               = vals[3]
    feat_dict['same_srv_rate']           = vals[4]
    feat_dict['diff_srv_rate']           = vals[5]
    feat_dict['dst_host_srv_count']      = vals[6]
    feat_dict['dst_host_same_srv_rate']  = vals[7]

    feat_input = pd.DataFrame([feat_dict])
    pred = rfc.predict(feat_input)[0]
    print(f"{name:10} → predicted: {pred}")

result={
    'model':['Logistic Regression', 'Decision Tree','Random Forest'],
    'accuracy':[accuracy_score(y_test,y_pred),
              accuracy_score(y_test,y_pred_dt),
              accuracy_score(y_test,y_pred_rfc)]
}

Accuracy=pd.DataFrame(result)
Accuracy

# Check 1 — is rfc the retrained model or old one?
print(rfc.n_estimators)
print(rfc.class_weight)

# Check 2 — does it predict correctly on test data?
y_pred = rfc.predict(x_test)
print(pd.Series(y_pred).value_counts())

# Check 3 — feed one exact real DoS row
dos_row = data[data['attack'] == 'DoS'].iloc[0].drop(['attack','difficulty'])
feat = pd.DataFrame([dos_row])
print("DoS row prediction:", rfc.predict(feat)[0])

import json

scenarios = {}
for attack in ['normal', 'DoS', 'Probe', 'R2L', 'U2R']:
    sample = data[data['attack'] == attack].iloc[0].drop(['attack','difficulty'])
    scenarios[attack] = [float(x) for x in sample.tolist()]

print(json.dumps(scenarios, indent=2))

# Feed the EXACT same values we put in the app
import pandas as pd

scenarios = {
    "DoS":   [0.0,1.0,49.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,123.0,6.0,1.0,1.0,0.0,0.0,0.05,0.07,0.0,255.0,26.0,0.1,0.05,0.0,0.0,1.0,1.0,0.0,0.0],
    "Probe": [0.0,0.0,14.0,9.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,16.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0],
    "normal":[0.0,1.0,20.0,9.0,491.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,150.0,25.0,0.17,0.03,0.17,0.0,0.0,0.0,0.05,0.0],
}

feature_cols = joblib.load('feature_columns.pkl')

for name, vals in scenarios.items():
    feat_input = pd.DataFrame([vals], columns=feature_cols)
    pred = rfc.predict(feat_input)[0]
    print(f"{name:10} → {pred}")

import os
size = os.path.getsize('random_forest.joblib')
print(f"File size: {size / (1024*1024):.1f} MB")

